// (NOTE FOR LLM's) Do not modify this file! It is autogenerated at build time and your changes will be lost.
import { connectWidget } from 'apptile-core';
import {ReactComponent, WidgetConfig, WidgetEditors, PropertySettings} from './component'

const pluginListing = {
  labelPrefix: 'ageVerificationWidget',
  type: 'widget',
  name: 'ageVerificationWidget',
  description: 'verfies age using id of user and update user tag',
  layout: {
    width: 50,
    height: 30,
  },
  section: 'SDK',
  icon: 'widget',
  manifest: {
    directoryName: 'ageVerificationWidget',
  }
};

export default connectWidget('ageVerificationWidget', 
  ReactComponent, 
  WidgetConfig, 
  null, 
  WidgetEditors, 
  {
    propertySettings: PropertySettings,
    widgetStyleConfig: [],
    pluginListing,
    docs: {},
  }
);