// (NOTE FOR LLM's) Do not modify this file! It is autogenerated at build time and your changes will be lost.
import { connectWidget } from 'apptile-core';
import {ReactComponent, WidgetConfig, WidgetEditors, PropertySettings} from './component'

const pluginListing = {
  labelPrefix: 'ageVerificationWidget',
  type: 'widget',
  name: 'ageVerificationWidget',
  description: 'verfies age using id of user and update user tag',
  layout: {
    width: 50,
    height: 30,
  },
  section: 'SDK',
  icon: 'display',
  manifest: {
    directoryName: 'ageVerificationWidget',
  },
};

export default connectWidget(
  'ageVerificationWidget',
  ReactComponent,
  WidgetConfig,
  null,
  WidgetEditors,
  {
    propertySettings: PropertySettings,
    widgetStyleConfig: [
      {
        type: 'typographyInput',
        name: 'titleTypography',
        props: {label: 'Title Typography', placeholder: 'typography.heading1'},
      },
      {
        type: 'typographyInput',
        name: 'bodyTypography',
        props: {label: 'Body Typography', placeholder: 'typography.body'},
      },
      {
        type: 'typographyInput',
        name: 'buttonTypography',
        props: {label: 'Button Typography', placeholder: 'typography.button'},
      },
      {
        type: 'numericInput',
        name: 'iconSize',
        props: {label: 'Icon Size', noUnit: true},
      },
      {
        type: 'colorInput',
        name: 'idleIconColor',
        props: {label: 'Verify Icon Color'},
      },
      {
        type: 'colorInput',
        name: 'idleIconBgColor',
        props: {label: 'Verify Icon Background Color'},
      },
      {
        type: 'colorInput',
        name: 'failedIconColor',
        props: {label: 'Failed Icon Color'},
      },
      {
        type: 'colorInput',
        name: 'failedIconBgColor',
        props: {label: 'Failed Icon Background Color'},
      },
      {
        type: 'colorInput',
        name: 'backgroundColor',
        props: {label: 'Background Color'},
      },
      {
        type: 'colorInput',
        name: 'accentColor',
        props: {label: 'Accent Color (icons & primary button)'},
      },
      {type: 'colorInput', name: 'titleColor', props: {label: 'Title Color'}},
      {
        type: 'colorInput',
        name: 'failedTitleColor',
        props: {label: 'Error Title Color'},
      },
      {
        type: 'colorInput',
        name: 'bodyTextColor',
        props: {label: 'Body Text Color'},
      },
      {
        type: 'colorInput',
        name: 'retryButtonBackgroundColor',
        props: {label: 'Retry Button Color'},
      },
      {
        type: 'colorInput',
        name: 'primaryButtonTextColor',
        props: {label: 'Verify Button Text Color'},
      },
      {
        type: 'colorInput',
        name: 'retryButtonTextColor',
        props: {label: 'Retry Button Text Color'},
      },
    ],
    pluginListing,
    docs: {},
  },
);