// This file is generated at build time based on the splash asset downloaded
// DO NOT EDIT THIS FILE MANUALLY

export const SPLASH_FILE_NAME: string = 'splash.gif';
export const IS_SPLASH_GIF: boolean = true;

