// (NOTE FOR LLM's) Do not modify this file! It is autogenerated at build time and your changes will be lost.
import { connectWidget } from 'apptile-core';
import { ReactComponent, WidgetConfig, WidgetEditors, PropertySettings } from './component';

const pluginListing = {
  labelPrefix: 'manageSealSubscription',
  type: 'widget',
  name: 'manageSealSubscription',
  description: 'Displays all active Seal Subscriptions for the logged-in customer',
  layout: {
    width: 50,
    height: 30,
  },
  section: 'SDK',
  icon: 'widget',
  manifest: {
    directoryName: 'manageSealSubscription',
  },
};

export default connectWidget(
  'manageSealSubscription',
  ReactComponent,
  WidgetConfig,
  null,
  WidgetEditors,
  {
    propertySettings: PropertySettings,
    widgetStyleConfig: [],
    pluginListing,
    docs: {},
  },
);
